name: solidart_lint
description: solidart_lint is a developer tool for users of solidart, designed to help stop common issues and simplify repetitive tasks
version: 2.0.0-dev.2
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart~dev
topics:
  - state-management
  - signals
  - linter

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  collection: ^1.18.0
  custom_lint_builder: ^0.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  solidart: ^2.0.0-dev.1
  flutter_solidart: ^2.0.0-dev.1
