name: solidart_lint
description: solidart_lint is a developer tool for users of solidart, designed to help stop common issues and simplify repetitive tasks
version: 1.0.1
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart
topics:
  - state-management
  - signals
  - linter

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.2.0
  analyzer_plugin: ^0.11.3
  collection: ^1.17.2
  custom_lint_builder: ^0.5.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  solidart: ^1.2.0
  flutter_solidart: ^1.4.0
