name: solidart_lint
description: solidart_lint is a developer tool for users of solidart, designed to help stop common issue and simplify repetetive tasks
version: 0.1.0
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^5.7.1
  analyzer_plugin: ^0.11.2
  collection: ^1.17.0
  custom_lint_builder: ^0.3.2
  solidart: ^0.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
