name: _
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/flutter_solidart
  - packages/flutter_solidart/example
  - packages/solidart
  - packages/solidart_devtools_extension
  - packages/solidart_lint
  - packages/solidart_hooks
  - packages/solidart_hooks/example
  - examples/counter
  - examples/github_search
  - examples/todos
  - examples/toggle_theme
  - examples/infinite_scroll
  - examples/auth_flow

dev_dependencies:
  reactivity_benchmark: ^0.0.1

flutter:
  uses-material-design: true
