name: solidart_example
description: "An example of a Flutter project combining disco and solidart."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  disco: ^1.0.0
  flutter:
    sdk: flutter
  flutter_solidart: ^2.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
