name: solidart
description: A simple State Management solution for Dart applications inspired by SolidJS
version: 1.1.0
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart~dev
topics:
  - state-management
  - signals

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1
  collection: ^1.17.2

dev_dependencies:
  mockito: ^5.4.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0+1
