name: solidart
description: A simple State Management solution for Dart applications inspired by SolidJS
version: 1.2.1
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart~dev
topics:
  - state-management
  - signals

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  meta: ^1.9.1

dev_dependencies:
  mockito: ^5.4.2
  test: ^1.24.9
  very_good_analysis: ^5.1.0
