name: solidart
description: A simple State Management solution for Dart applications inspired by SolidJS
repository: https://github.com/nank1ro/solidart
documentation: https://docs.page/nank1ro/solidart~dev
topics:
  - state
  - signals
  - reactive

version: 2.0.0-dev.4
resolution: workspace
environment:
  sdk: ^3.6.0

dependencies:
  alien_signals: ^0.0.12
  meta: ^1.11.0

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.25.3
  very_good_analysis: ^5.1.0
